### ISSUE TITLE
Suitable Python version to run this repo

### ISSUE THREAD

**Issue by quantrung9** [corey-snyder/STREETS#11]
Hi @corey-snyder ,

Sorry for bother you again. I want to run this repo to reproduce the result, but I don't know which Python version should I use so that the following packages can be run:
```
torchvision==0.3.0
Keras==2.1.0
pip==8.1.1
torch==1.1.0
```

Because you did not use any virtualenv tools like `pipenv` or `poetry` to manage, so I'm not sure which Python version were used.

I am looking forward to hearing from you soon.

**Comment by corey-snyder** [comment]
I believe Python 3.6.9 was used. I apologize for not being certain on this.
