### ISSUE TITLE
State inference data labels

### ISSUE THREAD

**Issue by codeoxvf** [corey-snyder/STREETS#24]
Hello, first I'd like to thank you for this very useful dataset. I have a question regarding the labels in the JSON file for the traffic state data. I was under the impression that it was a binary variable of free-flow (F) and queue (Q)? But the JSON contains about 200 entries with a 'B' and 1 with an 'I'. What do these refer to? Thanks!

**Comment by corey-snyder** [comment]
Hello, thanks for the question!

The 'B' entries refer to "bad images" I believe. These could be images where the PTZ camera is in motion and the image is very blurry, other camera issues, or severe weather issues. Basically, images where we can't tell what is going on.

The one "I" image may just be a typo. I apologize for the confusion on that, but I would just skip that image.

Hope that helps!

**Comment by codeoxvf** [comment]
Thank you so much! In hindsight it seems quite obvious after sorting and looking through them
