### ISSUE TITLE
Traffic prediction feature vector repeats elements

### ISSUE THREAD

**Issue by shehel** [corey-snyder/STREETS#6]
Hope I didn't miss anything but it seems like `build_feature_vector_chunk()` in _benchmark/trafficprediction/benchmarkutils.py_ is not doing what it should. 
If not mistaken, it should be building a feature vector by concatenating last L count elements and the state information if specified. However, at present it simply appends the same element as seen in line 183 `chunk.append(sensor_data[idx-history]['count'])` L times. I noticed that this doesn't affect the results in some algorithms but gives inconsistent results in others like linear regression. Ideally it should improve all results.

**Comment by corey-snyder** [comment]
Thank you for catching this! You are right and I have pushed the required fix.
