### ISSUE TITLE
some params meaning?

### ISSUE THREAD

**Issue by Winter0506** [corey-snyder/STREETS#7]
Hello, I want to ask you some params meaning, I know the `for K in [0, 1, 2]:` mean the sensor itself and it's 1-hop， 2-hop; And I think `for history in [3, 6]:` mean the 20 minutes and 50 minutes in the past; `for the horizon in [3, 6, 9]:` mean the 20 minutes, 50 minutes, 80 minutes in the future, Can you tell me whether this is correct or not?
Moreover, I want to know **fit_state** and **fit_full** meaning?

**Comment by corey-snyder** [comment]
Thank you for these questions! I plan to update this repo in the near future to improve the clarity and diversity of benchmarks.

Now, for your questions...

- K is in fact the size of the "K-hop" neighborhood as you describe
- history is the time in the past; however, note that the time span depends on the chosen sampling period T. We use T=5 in the paper which would mean history=3 gives us samples at present time, five minutes, and ten minutes in the past, for example
- horizon is computed similarly except for predicting into the future. Using the previous example, horizon=3 would predict 3*T=15 minutes in the future.
- fit_state and fit_full are flags for incorporating the traffic state inference information we discuss in pages 7 and 8 of [our NeurIPS 2019 paper](https://papers.nips.cc/paper/2019/hash/ee389847678a3a9d1ce9e4ca69200d06-Abstract.html). fit_state will enable training for separate estimators conditioned on the future sample's traffic state ('queue' or 'free-flow') while fit_full makes no use of this information and trains one estimator on all of the data independent of the inferred traffic state.

I hope this helps!

**Comment by Winter0506** [comment]
Thank you very much for your reply, it is very helpful to me
