### ISSUE TITLE
How the viewclassifiers created for each camera location?

### ISSUE THREAD

**Issue by quantrung9** [corey-snyder/STREETS#9]
Hi @corey-snyder,

I saw the [dataset](https://databank.illinois.edu/datasets/IDB-3671567 ) has viewclassifiers.zip contains .joblib files for the K-Nearest Neighbor classifier at each camera location.

In the paper you only mentioned about the 2-hop-neighbors will deliver a better performance. I think it would be better if you could describe how they were created and used.

Thank you so much.

**Comment by corey-snyder** [comment]
The K-hop neighborhoods are constructed by the ``load_K_hop_neighborhood`` function in the ``benchmark/trafficprediction/benchmarkutils.py`` file. Related utility functions are also contained in that file.

The view classifiers are for classifying the direction of a given camera. Recall that each camera rotates between 2, 3, or 4 different directions. While the data from each direction is supposed to be published separately, these publicly accessible cameras often are facing the incorrect direction. These view classifiers allow us to correct such mistakes while constructing the dataset.

I hope that answers your questions.

**Comment by quantrung9** [comment]
Your answer is very clear. Thank you @corey-snyder.
